import { useEffect, useState } from "react";

function InspectionReports() {
const [inspections, setInspections] = useState([]);
const [loading, setLoading] = useState(true);
const [error, setError] = useState("");

const API_URL = "http://https://visioninspectai-backend.onrender.com";

useEffect(() => {
fetch(`${API_URL}/inspections`)
.then(async (response) => {
if (!response.ok) {
throw new Error("Inspection request failed: ${response.status}");
}

    return response.json();
  })
  .then((data) => {
    if (!data.success) {
      throw new Error("Inspection reports could not be loaded.");
    }

    setInspections(data.inspections || []);
    setError("");
  })
  .catch((err) => {
    console.error("Inspection reports error:", err);
    setError(
      "Unable to load inspection reports. Please make sure the backend is running."
    );
  })
  .finally(() => {
    setLoading(false);
  });

}, []);

return (
<div
className="page-container"
style={{
padding: "40px",
minHeight: "100vh",
background: "#0f172a",
color: "white",
}}
>
<h1>📄 Inspection Reports</h1>

  <p style={{ color: "#94a3b8" }}>
    View actual inspection reports generated by the AI system.
  </p>

  {loading && (
    <p style={{ marginTop: "30px", color: "#38bdf8" }}>
      Loading inspection reports...
    </p>
  )}

  {error && (
    <div
      style={{
        marginTop: "30px",
        padding: "20px",
        background: "#1e293b",
        borderRadius: "12px",
        color: "#f87171",
      }}
    >
      {error}
    </div>
  )}

  {!loading && !error && inspections.length === 0 && (
    <div
      style={{
        marginTop: "30px",
        padding: "25px",
        background: "#1e293b",
        borderRadius: "12px",
        color: "#94a3b8",
      }}
    >
      No inspection records found in the database.
    </div>
  )}

  {!loading && !error && inspections.length > 0 && (
    <div
      style={{
        marginTop: "30px",
        overflowX: "auto",
        background: "#1e293b",
        borderRadius: "15px",
        padding: "10px",
        boxShadow: "0 10px 30px rgba(0,0,0,0.25)",
      }}
    >
      <table
        style={{
          width: "100%",
          borderCollapse: "collapse",
          color: "white",
          textAlign: "center",
        }}
      >
        <thead>
          <tr style={{ background: "#2563eb" }}>
            <th style={{ padding: "15px" }}>Report ID</th>
            <th style={{ padding: "15px" }}>Product Image</th>
            <th style={{ padding: "15px" }}>Result</th>
            <th style={{ padding: "15px" }}>Prediction</th>
            <th style={{ padding: "15px" }}>Confidence</th>
            <th style={{ padding: "15px" }}>Inspection Result</th>
          </tr>
        </thead>

        <tbody>
          {inspections.map((inspection, index) => {
            const isGood = inspection.result === "GOOD";

            return (
              <tr
                key={`${inspection.filename}-${index}`}
                style={{
                  background:
                    index % 2 === 0 ? "#0f172a" : "#111827",
                  borderBottom: "1px solid #334155",
                }}
              >
                <td style={{ padding: "15px", fontWeight: "bold" }}>
                  R{String(index + 1).padStart(3, "0")}
                </td>

                <td
                  style={{
                    padding: "15px",
                    color: "#cbd5e1",
                  }}
                >
                  {inspection.filename}
                </td>

                <td
                  style={{
                    padding: "15px",
                    color: isGood ? "#22c55e" : "#ef4444",
                    fontWeight: "bold",
                  }}
                >
                  {inspection.result}
                </td>

                <td style={{ padding: "15px" }}>
                  {inspection.prediction}
                </td>

                <td
                  style={{
                    padding: "15px",
                    color: "#38bdf8",
                    fontWeight: "bold",
                  }}
                >
                  {inspection.confidence ?? 0}%
                </td>

                <td
                  style={{
                    padding: "15px",
                    color: isGood ? "#22c55e" : "#f97316",
                  }}
                >
                  {inspection.inspection_result}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  )}
</div>

);
}

export default InspectionReports;